datasets:
  raw:
    google:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/sales/google.csv
      driver_params: {}
  
    product_manufacturer_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/sales/product_manufacturer_list.csv
      driver_params: {}
      
    sales_data:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/sales/sales_data.csv
      driver_params: {}
      
    social_media_data:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/sales/social_media_data.csv
      driver_params: {}
      
    Theme_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/sales/Theme_list.csv
      driver_params: {}
      
    Theme_product_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/sales/Theme_product_list.csv
      driver_params: {}
  
  cleaned:
    orders:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/sales/orders.parquet
      driver_params: {}

    product:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/sales/product.parquet
      driver_params: {}

    sales:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/sales/sales.parquet
      driver_params: {}

  processed:
    sales:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/processed/sales/sales.parquet
      driver_params: {}

  train:
    sales:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/train/sales/features.parquet
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/train/sales/target.parquet
        driver_params:
          save:
            index: False
  test:
    sales:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/sales/features.parquet
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/sales/target.parquet
        driver_params:
          save:
            index: False
  score:
    sales:
      output:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/sales/scored_output.parquet
        driver_params:
          save:
            index: False